function pts=ScanDatFile(filestr)
%function pts=ScanDatFile(filestr)
%  scan the 'dat' file generated by T2e CSI 'laser_log' command
%
% Zhen Song
fid=fopen(filestr);
tline=fgets(fid);% first line: Data from laser
tline=fgets(fid);% second line: blank 
pts=[];
while tline~=-1
    pts=[pts, fscanf(fid,'[%f,%f,%f]')];
    tline=fgets(fid);
end
fclose(fid);
